FR-96 | Tag Component
wesionaryTEAM/w-design pull request #19
Opened 2024-04-23 03:54 UTC by rodanr

# Overview 📖

Explain the purpose of this PR and provide context for the changes.

**🔖 Jira ticket:** [FR-96](https://wesionary-team.atlassian.net/browse/FR-96?atlOrigin=eyJpIjoiMjMzNWJjNGZkNmM2NGI3N2I4OGM5YTZjMDgxYjUwYzIiLCJwIjoiaiJ9)

## Features 🛠️

List of features or changes included in this PR:

- Tag Component
- Storybook for Tag Component

## Screenshots 📸
<img width="1022" alt="image" src="https://github.com/wesionaryTEAM/w-design/assets/56137447/2ba6fb7a-df7c-43f3-9b41-62ca10911c49">

## Dependencies 📦

None

## Environment Changes 🔍

None

## Testing 🧪

Run `yarn storybook`
Test the component

## Checklist ✅

- [x] Tested the component
- [x] Component looks fine

2024-04-26 05:03 UTC, Binabh commented on src/components/atoms/Tag/Tag.stories.tsx
How about adding more stories showcasing different variants/attributes? Things like color, shape, location can be changed but are not made accessible in storybook story.
🤔

2024-04-26 05:14 UTC, Binabh commented on src/components/atoms/Tag/Tag.stories.tsx
Seems like issue was with autodocs not working with lower node version. Resolved.

2024-04-26 05:15 UTC, Binabh approved these changes
LGTM 🚀

2024-04-29 04:27 UTC, itSubeDibesh approved these changes
LGTM 🙇‍♂️

2024-04-29 04:51 UTC, manojpudasaini requested changes

2024-04-29 04:51 UTC, manojpudasaini commented on src/components/atoms/Tag/index.tsx
> +  showCloseButton?: boolean;
It would be better to expose the text styles and button styles props for more customization.🙇

2024-04-29 04:51 UTC, manojpudasaini commented on src/components/atoms/Tag/index.tsx
> +        rootStyles({ size, color, shape, location })
Also, classname for root style can be included 🙇

2024-04-29 05:37 UTC, rodanr commented
@manojpudasaini Thank you for the suggestions. I have made the changes to ur request. Please review when you get time.

2024-05-22 06:56 UTC, manojpudasaini approved these changes
LGTM 🚀

2024-06-07 04:47 UTC, balraaz15 approved these changes
LGTM 🙇

2024-11-11 09:56 UTC, SudeepTimalsina approved these changes
LGTM 🙇

2024-11-11 09:57 UTC, merged